[package]
name = "recursia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1
#speed up compilation by removing debugger symbols (stack traces still work)
debug = 0

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

#TODO: uncomment for actual release builds
#also look into this: https://nnethercote.github.io/perf-book/build-configuration.html#link-time-optimization
#[profile.release]
#lto = true
debug = true

[dependencies]
ahash = "0.8.3"
#TODO: remove dynamic_linking/trace_tracy for releases (automate this)
#TODO: add features ktx2 and zstd to enable better texture performance and compression when using ktx2 textures
#TODO: maybe enable wayland feature?
bevy = { version = "0.11.0", features = ["trace_tracy"] }
bracket-noise = "0.8.7"
dashmap = "5.4.0"
futures-lite = "1.13.0"
serde = { version = "1.0.162", features = ["derive"] }
leafwing-input-manager = "0.10.0"
bevy-inspector-egui = "0.19.0"

#TODO: check if parallel makes things faster once I have many physics objects
bevy_rapier3d = { version = "0.22.0", features = [ "simd-stable", "debug-render-3d", "parallel" ] }
#changes merged, can go back to the crates.io version when it gets updated next
big-brain = {git = "https://github.com/jim-works/big-brain_set_unchecked.git" }
#big-brain = "0.18.0"
bincode = "1.3.3"
rusqlite = { version = "0.29.0", features = ["bundled"] }
r2d2_sqlite = "0.22.0"
r2d2 = "0.8.10"
rand = "0.8.5"
rand_distr = "0.4.3"
itertools = "0.11.0"
futures-timer = "3.0.2"

