[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = { workspace = true }
bevy = { workspace = true }
leafwing-input-manager = { workspace = true }

engine = { path = "../engine" }
util = { path = "../util" }
