[package]
name = "waves"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true }

engine = { path = "../engine" }
util = { path = "../util" }
actors = { path = "../actors" }
